labextension:
  factory:
    module: 'dask.distributed'
    class: 'LocalCluster'
    args: []
    kwargs: {}
  default:
    workers: null
    adapt:
      minimum: 0
      maximum: 10
  initial:
  - name: "Local Cluster"
    workers: null
    adapt:
      minimum: 1
      maximum: 10
