repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-import-order, flake8-print]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: ["-L", "coffea_casa", "tests", "docs/*rst"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        name: mypy with Python 3.7
        files: coffea_casa
        additional_dependencies: ["dask", "distributed"]
        args: ["--python-version=3.7"]
    -   id: mypy
        name: mypy with Python 3.9
        files: coffea_casa
        additional_dependencies: ["dask", "distributed"]
        args: ["--python-version=3.9"]