{{- if .Values.devaf.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: xcache-token
  namespace: {{.Release.Namespace}}
type: Opaque
data:
{{ if .Values.devaf.testtoken }}
  token: {{printf "%s" .Values.devaf.testtoken | b64enc }}
{{ end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: dask-certs
  namespace: {{.Release.Namespace}}
type: Opaque
data:
{{ if .Values.devaf.testpem }}
  ca.pem: {{ printf "%s" .Values.devaf.testpem | b64enc }}
  hostcert.pem: {{ printf "%s" .Values.devaf.testpem | b64enc }}
  usercert.pem: {{ printf "%s" .Values.devaf.testpem | b64enc }}
  ca.key: {{ printf "%s" .Values.testpem | b64enc }}
{{ end }}
{{- end }}
