apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hub-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  {{ if .Values.servicex.enabled }}
  XCACHE_HOST = {{ .Values.servicex.host }}
  {{ end }}
  BEARER_TOKEN_FILE = {{ .Values.tokens.bearer_token | default "/etc/cmsaf-secrets/xcache_token" | quote }}
  XRD_PLUGINCONFDIR = {{ .Values.tokens.xrdauthz_plugin_confdir | default "/opt/conda/etc/xrootd/client.plugins.d/" | quote }}
  XRD_PLUGIN = {{ .Values.tokens.xrdauthz_plugin | default "/opt/conda/lib/libXrdClAuthzPlugin.so" | quote }}
  LD_LIBRARY_PATH = {{ .Values.tokens.xrdauthz_ldlibrarypath | default "/opt/conda/lib/" | quote }}
  {{ if .Values.servicex.enabled }}
  SERVICEX_HOST = {{ .Values.servicex.host }}
  {{ end }}
  {{ if .Values.dask.enabled }}
  DASK_BASE_DOMAIN = {{ .Values.dask.dask_base_domain }}
  {{ end }}
  {{ if .Values.auth.enabled }}
  OAUTH_CALLBACK_URL = {{ .Values.auth.oauth_callback_url }}
  OAUTH2_AUTHORIZE_URL = {{ .Values.auth.oauth_authorize_url }}
  OAUTH2_TOKEN_URL = {{ .Values.auth.oauth_token_url }}
  {{ end }}