labextension:
  factory:
    module: 'dask_jobqueue'
    class: 'HTCondorCluster'
    args: []
    kwargs: {}
                                     
  default:
    workers: 1
    adapt:
      minimum: 1
      maximum: 100

  initial:
    - name: "default"
      workers: 1
      adapt:
        minimum: 1
        maximum: 100

