distributed:
  version: 2

  # TODO: we don't want to shut it down probably (?)
  # scheduler:
    # idle-timeout: 3600s   # Shut down after this duration, like "1h" or "30 minutes".

  comm:
    require-encryption: True # Whether to require encryption on non-local comms

    tls:
      ciphers: null   # Allowed ciphers, specified as an OpenSSL cipher string.
      ca-file: "/etc/cmsaf-secrets/ca.pem"   # Path to a CA file, in pem format, optional
      scheduler:
        cert: "/etc/cmsaf-secrets/hostcert.pem"    # Path to certificate file for scheduler.
        key: "/etc/cmsaf-secrets/hostcert.pem"     # Path to key file for scheduler.
      worker:
        key: null
        cert: null
      client:
        key: "/etc/cmsaf-secrets/hostcert.pem"  # Path to certificate file for client.
        cert: "/etc/cmsaf-secrets/hostcert.pem"  # Path to key file for client.

  dashboard:
    link: "/user/{JUPYTERHUB_USER}/proxy/{port}/status"

  admin:
    tick:
      limit: 5s # time allowed before triggering a warning
