
# This configuration is meant to map lookups of local.coffea.casa to the
# ClusterIP of JupyterHub's proxy-public service
#
# ref: https://github.com/jupyterhub/pebble-helm-chart/blob/master/pebble/values.yaml
#
coredns:
  corefileSegment: |-
    template ANY ANY local.jovyan.org {
      answer "{{ .Name }} 60 IN CNAME proxy-public.{$PEBBLE_NAMESPACE}.svc.cluster.local"
    }
