---
# Disable/enable RBAC
rbac:
  enabled: true
  traefik:
      serviceAccountName: traefik

# traefik nested config relates to the traefik Pod and Traefik running within it
# that is acting as a proxy for traffic towards the gateway or user created
# DaskCluster resources.
traefik:
  enabled: true
  service:
    type: LoadBalancer
    port: 
      daskshduler: 8786
      daskworker: 8788
  # Number of instances of the proxy to run
  replicas: 1

  # Any annotations to add to the proxy pods
  annotations: {}

  # Resource requests/limits for the proxy pods
  resources: {}

  # The image to use for the proxy pod
  image:
    name: traefik
    tag: "v2.3.7"
    pullPolicy: IfNotPresent
  imagePullSecrets: []

  # Any additional arguments to forward to traefik
  additionalArguments: []

  # The proxy log level
  loglevel: WARN

  # Whether to expose the dashboard on port 9000 (enable for debugging only!)
  dashboard: false

# Disable/enable ServiceX as a dependency
servicex:
  enabled: false
  #host: "http://coffea-casa-servicex-app:8000"

# Jupyterhub settings
jupyterhub: 
  hub:
    config:
      Authenticator:
        admin_users:
        - test
      allowed_users:
        - test
    DummyAuthenticator:
      password: Test_Test_Test
    JupyterHub:
      authenticator_class: dummy
    initContainers:
      - name: git-clone-templates
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --branch=master
          - --depth=1
          - --
          - https://github.com/clundst/jh_custom_html
          - /etc/jupyterhub/custom
        securityContext:
          runAsUser: 0
    networkPolicy:
      enabled: false
    readinessProbe:
      periodSeconds: 10
    db:
      pvc:
        storageClassName: standard
    image:
      name: hub.opensciencegrid.org/coffea-casa/k8s-hub-coffea-casa
      tag: 0.11.1 
    extraEnv:
      DASK_BASE_DOMAIN: localhost
      CONDOR_ENABLED: 'True'
      SERVICEX_ENABLED: 'False'
  proxy:
    chp:
      livenessProbe:
        initialDelaySeconds: 30
      readinessProbe:
        periodSeconds: 10
      networkPolicy:
        enabled: false
    extraEnv:
      # explicit notation (the "name" field takes precedence)
      CHP_NAMESPACE:
        name: CHP_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    https:
      enabled: true
      hosts:
        - coffea-opendata.casa
      letsencrypt:
        contactEmail: cms-support@cse.unl.edu
    service:
      type: LoadBalancer
      nodePorts:
        http:
        https:
      loadBalancerIP: 127.0.0.1

  singleuser:
    networkPolicy:
      enabled: false
    spec:
      securityContext:
        runAsUser: 6440
    uid: 6440
    gid: 11265
    extraLabels:
      jhub_user: '{username}'
    lifecycleHooks:
      postStart:
        exec:
          command: ['bash', '-c', 'mkdir -p /home/cms-jovyan/.condor/tokens.d/ && cp -f /etc/cmsaf-secrets/condor_token /home/cms-jovyan/.condor/tokens.d/condor_token']
    storage:
      homeMountPath: /home/cms-jovyan/
      dynamic:
        storageClass: standard
    image:
      name: daskdev/dask-notebook
      tag: 2021.6.0
    defaultUrl: "/lab"
    profileList:
      - display_name: "Coffea Base Image"
        description: "Coffea-casa build with coffea 0.7.11/dask 2021.11.2/condor and cheese"
        kubespawner_override:
          image: hub.opensciencegrid.org/coffea-casa/coffea-casa-analysis:2021.12.10
          imagePullPolicy: Always
          securityContext:
            runAsUser: 6440
            runAsGroup: 11265
            allowPrivilegeEscalation: False
            RunAsNonRoot: true
        default: true
    extraContainers:
    - name: dask-worker
      volumeMounts:
      - mountPath: /etc/cmsaf-secrets
        name: cmsaf-secrets
      image: hub.opensciencegrid.org/coffea-casa/coffea-casa-analysis:2021.12.10
      securityContext:
        runAsUser: 6440
        runAsGroup: 11265
        runAsNonRoot: True
      resources:
        limits:
          memory: 7Gi
          cpu: 2
      env:
        - name: COFFEA_CASA_SIDECAR
          value: 'True'
        - name: XCACHE_HOST
          value: "red-xcache1.unl.edu"
        - name: XRD_PLUGIN
          value: "/opt/conda/lib/libXrdClAuthzPlugin.so"
        - name: XRD_PLUGINCONFDIR
          value: "/opt/conda/etc/xrootd/client.plugins.d/"
        - name: BEARER_TOKEN_FILE
          value: "/etc/cmsaf-secrets/xcache_token"
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      command: ["/bin/bash", "-c", "cd /home/cms-jovyan; supervisord --nodaemon -c /etc/supervisor/supervisord.conf"]

  scheduling:
    userScheduler:
      enabled: false
