---
# Disable/enable RBAC
rbac:
  enabled: true
  traefik:
    serviceAccountName: traefik

# traefik nested config relates to the traefik Pod and Traefik running within it
# that is acting as a proxy for traffic towards the gateway or user created
# DaskCluster resources.
traefik:
  enabled: true
  service:
    type: LoadBalancer
    port:
      daskscheduler: 8786
      daskworker: 8788
  # Number of instances of the proxy to run
  replicas: 1
  # Any annotations to add to the proxy pods
  annotations: {}
  # Resource requests/limits for the proxy pods
  resources: {}
  # The image to use for the proxy pod
  image:
    name: traefik
    tag: "v2.3.7"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  # Any additional arguments to forward to traefik
  additionalArguments: []
  # The proxy log level
  loglevel: WARN
  # Whether to expose the dashboard on port 9000 (enable for debugging only!)
  dashboard: false

# Disable/enable ServiceX as a dependency
servicex:
  enabled: false
  host: "http://coffea-casa-servicex-app:8000"

xcache:
  enabled: true
  host: "red-xcache1.unl.edu"

dask:
  enabled: true
  dask_base_domain: localhost

auth:
  enabled: true
  oauth_callback_url: https://cms-auth.web.cern.ch/oauth_callback
  oauth_authorize_url: https://cms-auth.web.cern.ch/authorize
  oauth_token_url: https://cms-auth.web.cern.ch/token

tokens:
  bearer_token:
  xrdauthz_plugin_confdir:
  xrdauthz_plugin:
  xrdauthz_ldlibrarypath:

# Jupyterhub settings
jupyterhub:
  hub:
    config:
      Authenticator:
        admin_users:
        - coffea-casa-dev@cern.ch
      GenericOAuthenticator:
        login_service: CMS SSO
        token_url: https://cms-auth.web.cern.ch/token
        userdata_method: GET
        userdata_params:
          state: state
        userdata_url: https://cms-auth.web.cern.ch/userinfo
        username_key: email
      JupyterHub:
        authenticator_class: oauthenticator.generic.GenericOAuthenticator
    initContainers:
      - name: git-clone-templates
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --branch=master
          - --depth=1
          - --
          - https://github.com/clundst/jh_custom_html
          - /etc/jupyterhub/custom
        securityContext:
          runAsUser: 0
    networkPolicy:
      enabled: false
    readinessProbe:
      periodSeconds: 10
    db:
      pvc:
        storageClassName: rook-ceph-block
    image:
      name: jupyterhub/k8s-hub
      tag: 1.2.0
    command: ["sh", "-c"]
    args:
        -    pip install
               --cache-dir /srv/jupyterhub/.cache/pip
               pyjwt
               pymacaroons
          && jupyterhub
               --config /usr/local/etc/jupyterhub/jupyterhub_config.py
               --upgrade-db
    extraEnv:
      OAUTH2_AUTHORIZE_URL:
      OAUTH2_TOKEN_URL:
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      DASK_BASE_DOMAIN:

  proxy:
    chp:
      livenessProbe:
        initialDelaySeconds: 30
      readinessProbe:
        periodSeconds: 10
      networkPolicy:
        enabled: false
    extraEnv:
      # explicit notation (the "name" field takes precedence)
      CHP_NAMESPACE:
        name: CHP_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    https:
      enabled: true
      hosts:
        - coffea-opendata.casa
      letsencrypt:
        contactEmail: cms-support@cse.unl.edu
    service:
      type: LoadBalancer
      nodePorts:
        http:
        https:
      loadBalancerIP: 129.93.183.34

  singleuser:
    networkPolicy:
      enabled: false
    spec:
      securityContext:
        runAsUser: 6440
    uid: 6440
    gid: 11265
    extraLabels:
      jhub_user: '{username}'
    lifecycleHooks:
      postStart:
        exec:
          command: ['bash', '-c', 'mkdir -p /home/cms-jovyan/.condor/tokens.d/ && cp -f /etc/cmsaf-secrets/condor_token /home/cms-jovyan/.condor/tokens.d/condor_token']
    storage:
      homeMountPath: /home/cms-jovyan/
      dynamic:
        storageClass: rook-ceph-block
    image:
      name: daskdev/dask-notebook
      tag: 2021.6.0
    defaultUrl: "/lab"
    profileList:
      - display_name: "Coffea Base Image"
        description: "Coffea-casa image with coffea 0.7.5/dask/condor and cheese"
        kubespawner_override:
          image: coffeateam/coffea-casa:2021.07.22
          imagePullPolicy: Always
          securityContext:
            runAsUser: 6440
            runAsGroup: 11265
            allowPrivilegeEscalation: False
            RunAsNonRoot: true
        default: true
    extraContainers:
    - name: dask-worker
      volumeMounts:
      - mountPath: /etc/cmsaf-secrets
        name: cmsaf-secrets
      image: coffeateam/coffea-casa-analysis:2021.07.22
      securityContext:
        runAsUser: 6440
        runAsGroup: 11265
        runAsNonRoot: True
      resources:
        limits:
          memory: 7Gi
          cpu: 2
      env:
        - name: COFFEA_CASA_SIDECAR
          value: 'True'
        - name: XCACHE_HOST
          value:
        - name: XRD_PLUGIN
          value:
        - name: XRD_PLUGINCONFDIR
          value:
        - name: BEARER_TOKEN_FILE
          value:
        - name: WORKER_ID
          value:
      command: ["/bin/bash", "-c", "cd /home/cms-jovyan; supervisord --nodaemon -c /etc/supervisor/supervisord.conf"]

  scheduling:
    userScheduler:
      enabled: false
