ARG TAG="latest"
ARG NAME="coffeateam/cc-analysis-centos7"
FROM ${NAME}:${TAG}

USER root
LABEL maintainer="Oksana Shadura <ksu.shadura@gmail.com>"
# Try to see if CEPH_CONF works (https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/1.2.3/html/ceph_configuration_guide/configuration_file_structure)
ARG CEPH_DIR="/opt/ceph"
ARG CEPH_CONF=$CEPH_DIR"/ceph.conf"

# Hack for GH Actions
ARG GITHUB_ACTIONS="false"

# Configure environment
ENV CEPH_DIR $CEPH_DIR
ENV CEPH_CONF $CEPH_CONF

USER root
RUN yum -y update \
 && yum -y install \
    libradospp-dev librados2 rados-objclass-dev python3-rados ceph ceph-mon ceph-osd ceph-mgr ceph-mds ceph-common
# Preparing directories for Dask conf files, patches and job spool directory for HTCondor
RUN mkdir -p ${CEPH_DIR} && chown -R "${NB_USER}:${NB_GID}" ${CEPH_DIR}

USER ${NB_UID}

COPY skyhook/build-skyhook.sh /tmp/

RUN cd /tmp && \
    git clone \
        --branch arrow-master \
        --depth=1 \
        https://github.com/uccross/skyhookdm-arrow && \
        ./build-skyhook.sh

# Skyhook setup: Ceph configuration and Keyring
COPY ceph/ceph.conf ceph/keyring ${CEPH_DIR}/

USER root
# Cleanup
RUN rm -rf /tmp/* \
    && rm -rf $HOME/.cache/.pip/* \
    && mamba clean -tipsy \
    && jupyter lab clean \
    && jlpm cache clean \
    && npm cache clean --force \
    && find ${CONDA_DIR} -type f -name '*.a' -delete \
    && find ${CONDA_DIR} -type f -name '*.pyc' -delete \
    && find ${CONDA_DIR} -type f -name '*.js.map' -delete \
    && (find ${CONDA_DIR}/lib/python*/site-packages/bokeh/server/static -type f,l -name '*.js' -not -name '*.min.js' -delete || echo "no bokeh static files to cleanup") \
    && rm -rf ${CONDA_DIR}/pkgs

# Fix permissions for Dask/Ceph config files
RUN chown -R "${NB_USER}:${NB_GID}" ${CEPH_DIR}/keyring ${CEPH_DIR}/ceph.conf

USER $NB_USER
ENTRYPOINT ["tini", "-g", "--", "/usr/local/bin/prepare-env.sh"]
