charts:
  - name: coffea-casa
    imagePrefix: hub.opensciencegrid.org/coffea-casa/
    repo:
      git: coffeateam/coffea-casa
      published: https://coffeateam.github.io/coffea-casa/
    images:
      k8s-hub-coffea-casa:
        # We will not use the default build contextPath, and must therefore
        # specify the dockerfilePath explicitly.
        dockerfilePath: coffea-casa/docker/k8s-hub-coffea-casa/Dockerfile
        # Context to send to docker build for use by the Dockerfile. We pass the
        # root folder in order to allow the image to access and build the python
        # package.
        contextPath: coffea-casa/docker/k8s-hub-coffea-casa
        # To avoid chartpress to react to changes in documentation and other
        # things, we ask it to not trigger on changes to the contextPath, which
        # means we manually should add paths rebuild should be triggered on
        rebuildOnContextPathChanges: false
        # We manually specify the paths which chartpress should monitor for
        # changes that should trigger a rebuild of this image.
        paths:
          - coffea-casa/docker/k8s-hub-coffea-casa/Dockerfile
        valuesPath:
          - jupyterhub.hub.image
      coffea-casa:
        # We will not use the default build contextPath, and must therefore
        # specify the dockerfilePath explicitly.
        dockerfilePath: ../docker/coffea-casa/Dockerfile
        # Context to send to docker build for use by the Dockerfile. We pass the
        # root folder in order to allow the image to access and build the python
        # package.
        contextPath: ../docker/coffea-casa
        # To avoid chartpress to react to changes in documentation and other
        # things, we ask it to not trigger on changes to the contextPath, which
        # means we manually should add paths rebuild should be triggered on
        rebuildOnContextPathChanges: false
        # We manually specify the paths which chartpress should monitor for
        # changes that should trigger a rebuild of this image.
        paths:
          - ../docker/coffea-casa/Dockerfile
        valuesPath:
          - jupyterhub.singleuser.profileList.0.kubespawner_override.image
      #coffea-casa-analysis:
      #  # We will not use the default build contextPath, and must therefore
      #  # specify the dockerfilePath explicitly.
      #  dockerfilePath: ../docker/coffea-casa-analysis/Dockerfile
      #  # Context to send to docker build for use by the Dockerfile. We pass the
      #  # root folder in order to allow the image to access and build the python
      #  # package.
      #  contextPath: ../docker/coffea-casa-analysis
      #  # To avoid chartpress to react to changes in documentation and other
      #  # things, we ask it to not trigger on changes to the contextPath, which
      #  # means we manually should add paths rebuild should be triggered on
      #  rebuildOnContextPathChanges: false
      #  # We manually specify the paths which chartpress should monitor for
      #  # changes that should trigger a rebuild of this image.
      #  paths:
      #    - ../docker/coffea-casa-analysis/Dockerfile
      #  valuesPath: image