charts:
  - name: coffea-casa
    imagePrefix: hub.opensciencegrid.org/coffea-casa/
    #imagePrefix: jupyterhub/k8s-
    repo:
      git: coffeateam/coffea-casa
      published: https://coffeateam.github.io/coffea-casa/
    images:
      # hub, the container where JupyterHub, KubeSpawner, and the configured
      # Authenticator are running.
      #hub:
      #  valuesPath: jupyterhub.hub.image
      # secret-sync, a sidecar container running in the autohttps pod to next to
      # Traefik meant to sync a TLS certificate with a k8s Secret.
      #secret-sync:
      #  valuesPath: jupyterhub.proxy.secretSync.image

      # network-tools, an initContainer with iptables installed starting on user
      # pods to block access to the so called "cloud metadata server" for
      # security reasons.
      #network-tools:
      #  valuesPath: jupyterhub.singleuser.networkTools.image

      # image-awaiter, the only container inside the image-awaiter-job Pod
      # starting as part of `helm upgrade` in order to check that images have
      # been pulled by the hook-image-puller before helm starts doing additional
      # changes as part of the upgrade.
      #image-awaiter:
      #  valuesPath: jupyterhub.prePuller.hook.image

      # singleuser-sample, a primitive user container to start with.
      #singleuser-sample:
      #  valuesPath: jupyterhub.singleuser.image


      # FIXME: This section doesnt work
      #cc-ubuntu:
        # We will not use the default build contextPath, and must therefore
        # specify the dockerfilePath explicitly.
      #  dockerfilePath: ../docker/Dockerfile.cc-ubuntu
        # Context to send to docker build for use by the Dockerfile. We pass the
        # root folder in order to allow the image to access and build the python
        # package.
      #  contextPath: ../docker
        # To avoid chartpress to react to changes in documentation and other
        # things, we ask it to not trigger on changes to the contextPath, which
        # means we manually should add paths rebuild should be triggered on
      #  rebuildOnContextPathChanges: false
        # We manually specify the paths which chartpress should monitor for
        # changes that should trigger a rebuild of this image.
      #  paths:
      #    - ../docker/Dockerfile.cc-ubuntu
      #  valuesPath:
      #    - jupyterhub.singleuser.profileList.0.kubespawner_override.image

      #coffea-casa-analysis:
      #  # We will not use the default build contextPath, and must therefore
      #  # specify the dockerfilePath explicitly.
      #  dockerfilePath: ../docker/Dockerfile.cc-analysis-ubuntu
      #  # Context to send to docker build for use by the Dockerfile. We pass the
      #  # root folder in order to allow the image to access and build the python
      #  # package.
      #  contextPath: ../docker
      #  # To avoid chartpress to react to changes in documentation and other
      #  # things, we ask it to not trigger on changes to the contextPath, which
      #  # means we manually should add paths rebuild should be triggered on
      #  rebuildOnContextPathChanges: false
      #  # We manually specify the paths which chartpress should monitor for
      #  # changes that should trigger a rebuild of this image.
      #  paths:
      #    - ../docker/Dockerfile.cc-analysis-ubuntu
      #  valuesPath:
      #    - jupyterhub.singleuser.extraContainers.image
