# This configuration is meant to map lookups of local.jovyan.org to the
# ClusterIP of JupyterHub's proxy-public service
#
# ref: https://github.com/jupyterhub/pebble-helm-chart/blob/HEAD/pebble/values.yaml
#
coredns:
  corefileSegment: |-
    template ANY ANY coffea-test.casa {
      answer "{{ .Name }} 60 IN CNAME proxy-public.{$PEBBLE_NAMESPACE}.svc.cluster.local"
    }
