---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffea-casa.traefikName" . }}
spec:
  type: {{ .Values.traefik.service.type }}
  selector:
    app: {{- include "coffea-casa.traefikName" . }}
  ports:
    - name: TCP
      targetPort: 80
      port: 80
      name: http
    - name: TCP
      targetPort: 443
      port: 443
      name: https
    - protocol: TCP
      port: 8786
      targetPort: 8786
      name: dask
    - protocol: TCP
      port: 8788
      targetPort: 8788
      name: daskworker
    {{- if .Values.traefik.dashboard }}
    - name: traefik
      targetPort: 9000
      port: 9000
    {{- end }}