---
{{- if .Values.traefik.enabled }}
{{- if .Values.rbac.enabled -}}
{{- if not .Values.rbac.traefik.serviceAccountName -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "coffea-casa.traefikName" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "coffea-casa.traefikName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - middlewaretcps
      - ingressroutes
      - traefikservices
      - ingressroute
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
    verbs:
      - get
      - list
      - watch

# Give the hub the role to manage ingressroutetcps for dask
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "coffea-casa.traefikName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "coffea-casa.traefikName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "coffea-casa.traefikName" . }}
    namespace: "{{ .Release.Namespace }}"
{{- end }}
{{- end }}
{{- end }}