# Only test building images
name: PullRequest

on:
  pull_request:
    paths:
      - 'charts/coffea-casa/docker/**'
    branches:
      - master
      - develop

env:
  DOCKER_ORG: coffeateam
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: ["k8s-hub-coffea-casa"]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Image
      run: |
        cd charts/coffea-casa/docker/${{ matrix.IMAGE }}
        docker build --build-arg GITHUB_ACTIONS=$GITHUB_ACTIONS -t  ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR .
        
    # FIXME: add some tests
    #- name: Test Image
    #  run: |
    #    docker run -u 1000 -w /srv/test -v $PWD:/srv/test ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR ./run_tests.sh ${{ matrix.IMAGE }}
