# Only test building images
name: PullRequest-cc-analysis cc7
on:
  pull_request:
    paths:
      - 'docker/prepare-env/prepare-env-cc-analysis.sh'
      - 'docker/jupyterhub/**'
      - 'docker/dask/**'
      - 'docker/uproot/**'
      - 'docker/k8s-worker/**'
      - 'docker/Dockerfile.cc-analysis-centos7'
    branches:
      - master
      - develop
env:
  DOCKER_ORG: coffeateam
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [cc-analysis-centos7]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Image
      run: |
        cd docker
        docker build --build-arg GITHUB_ACTIONS=$GITHUB_ACTIONS -t  ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR -f Dockerfile.${{ matrix.IMAGE }} .
    - name: Export Full Conda Environment
      run: |
        docker run -e GITHUB_ACTIONS=$GITHUB_ACTIONS ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR conda list --export